using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ServerApp.ConstValue
{

    public static class DepartmentNames
    {
        public static readonly string[] Names = new string[]
        {
        "Department of Computer Science",
        "Department of Mathematics",
        "Department of Physics",
        "Department of Chemistry",
        "Department of Biology",
        "Department of English Literature",
        "Department of History",
        "Department of Political Science",
        "Department of Psychology",
        "Department of Sociology",
        "Department of Economics",
        "Department of Business Administration",
        "Department of Marketing",
        "Department of Finance",
        "Department of Education",
        "Department of Engineering",
        "Department of Environmental Science",
        "Department of Philosophy",
        "Department of Art and Design",
        "Department of Music",
        "Department of Performing Arts",
        "Department of Linguistics",
        "Department of Anthropology",
        "Department of Journalism and Mass Communication",
        "Department of Nursing",
        "Department of Medical Sciences",
        "Department of Dental Studies",
        "Department of Pharmacy",
        "Department of Public Health",
        "Department of Veterinary Science",
        "Department of Information Technology",
        "Department of Cybersecurity",
        "Department of Software Engineering",
        "Department of Data Science",
        "Department of Artificial Intelligence",
        "Department of Machine Learning",
        "Department of Robotics",
        "Department of Aerospace Engineering",
        "Department of Civil Engineering",
        "Department of Mechanical Engineering",
        "Department of Electrical Engineering",
        "Department of Chemical Engineering",
        "Department of Industrial Engineering",
        "Department of Materials Science",
        "Department of Astronomy",
        "Department of Marine Biology",
        "Department of Genetics",
        "Department of Microbiology",
        "Department of Biochemistry",
        "Department of Environmental Engineering",
        "Department of Renewable Energy",
        "Department of Geographic Information Systems",
        "Department of Urban Planning",
        "Department of International Relations",
        "Department of Peace and Conflict Studies",
        "Department of Criminology",
        "Department of Social Work",
        "Department of Theology",
        "Department of Religious Studies",
        "Department of Archaeology",
        "Department of Classics",
        "Department of Gender Studies",
        "Department of African Studies",
        "Department of Asian Studies",
        "Department of Latin American Studies",
        "Department of Middle Eastern Studies",
        "Department of History of Art",
        "Department of Film Studies",
        "Department of Media Studies",
        "Department of Communications",
        "Department of Creative Writing",
        "Department of Theatre Arts",
        "Department of Dance",
        "Department of Fashion Design",
        "Department of Graphic Design",
        "Department of Interior Design",
        "Department of Industrial Design",
        "Department of Architecture",
        "Department of Urban Design",
        "Department of Law",
        "Department of International Law",
        "Department of Environmental Law",
        "Department of Intellectual Property Law",
        "Department of Human Rights",
        "Department of Public Administration",
        "Department of Leadership Studies",
        "Department of Hospitality Management",
        "Department of Tourism Management",
        "Department of Culinary Arts",
        "Department of Event Management",
        "Department ofTransport and Logistics",
        "Department of Supply Chain Management",
        "Department of Project Management",
        "Department of Human Resources",
        "Department of Organizational Behavior",
        "Department of Strategy and Innovation",
        "Department of Operations Management",
        "Department of Risk Management",
        "Department of Ethics",
        "Department of Corporate Governance",
        "Department of E-commerce",
        "Department of Real Estate",
        "Department of Textile Engineering",
        "Department of Metallurgical Engineering",
        "Department of Geology",
        "Department of Oceanography",
        "Department of Environmental Conservation",
        "Department of Agronomy",
        "Department of Horticulture",
        "Department of Food Technology",
        "Department of Forestry",
        "Department of Animal Sciences",
        "Department of Plant Sciences",
        "Department of Soil Science",
        "Department of Agricultural Economics",
        "Department of Rural Development",
        "Department of Aquaculture",
        "Department of Health Administration",
        "Department of Rehabilitation Sciences",
        "Department of Speech-Language Pathology",
        "Department of Occupational Therapy",
        "Department of Physical Therapy",
        "Department of Nutrition and Dietetics",
        "Department of Biomedical Sciences",
        "Department of Neuroscience",
        "Department of Cognitive Science",
        "Department of Behavioral Sciences",
        "Department of Social Psychology",
        "Department of Community Psychology",
        "Department of Educational Psychology",
        "Department of Developmental Psychology",
        "Department of Clinical Psychology",
        "Department of Experimental Psychology",
        "Department of Music Therapy",
        "Department of Art Therapy",
        "Department of Dance Therapy",
        "Department of Drama Therapy",
        "Department of Language Education",
        "Department of Special Education",
        "Department of Curriculum Studies",
        "Department of Educational Leadership",
        "Department of Higher Education",
        "Department of Distance Education",
        "Department of Adult Education",
        "Department of Assessment and Evaluation",
        "Department of Gifted Education",
        "Department of Early Childhood Education",
        "Department of Secondary Education",
        "Department of Career and Technical Education",
        "Department of Learning Technologies",
        "Department of Instructional Design",
        "Department of Library and Information Science",
        "Department of Archival Studies",
        "Department of Record Management",
        "Department of Museum Studies",
        "Department of Heritage Conservation",
        "Department of Urban Studies",
        "Department of Rural Studies",
        "Department of Global Studies",
        "Department of Cultural Studies",
        "Department of Peace Studies",
        "Department of Education Policy",
        "Department of Educational Technology",
        "Department of Science Education",
        "Department of Math Education",
        "Department of Language and Literacy",
        "Department of Performing Arts Education",
        "Department of Agricultural Education",
        "Department of Art Education",
        "Department of Music Education",
        "Department of Social Studies Education"
        };
    }
}